BRICK          = 'brick'
BRICK_ROUNDED  = 'brick-rounded'
BRICK_MODIFIED = 'brick-modified'
BRICK_ARCH     = 'brick-arch'

TECHNIC           = 'technic'
TECHNIC_AXEL      = 'technic-axel'
TECHNIC_BRICK     = 'technic-brick'
TECHNIC_CONNECTOR = 'technic-connector'
TECHNIC_GEAR      = 'technic-gear'
TECHNIC_LIFTARM   = 'technic-leftarm'
TECHNIC_LINK      = 'technic-link'
TECHNIC_PIN       = 'technic-pin'
TECHNIC_PLATE     = 'technic-plate'
TECHNIC_STEERING  = 'technic-steering'
